services:
  nginx1:
    image: nginx:alpine
    container_name: nginx1
    expose:
      - "8080"
    command: ["/bin/sh","-c","sed -i 's/listen       80/listen 8080/' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]

  nginx2:
    image: nginx:alpine
    container_name: nginx2
    expose:
      - "8081"
    command: ["/bin/sh","-c","sed -i 's/listen       80/listen 8081/' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]

  # Simple TCP echo server on port 9000
  tcp-service:
    image: alpine:3.20
    container_name: tcp-service
    expose:
      - "9000"
    command: ["/bin/sh","-c","apk add --no-cache socat && socat -v tcp-l:9000,fork,reuseaddr -"]

  envoy:
    image: envoyproxy/envoy:v1.31.0
    container_name: envoy
    depends_on:
      - nginx1
      - nginx2
      - tcp-service
    ports:
      - "80:80"
      - "9901:9901"
    volumes:
      - ./http-tcp-discrimination.yaml:/etc/envoy/envoy.yaml:ro
    command: ["envoy","-c","/etc/envoy/envoy.yaml","-l","info"]
